# Cloud Build Configuration for Testing
# Runs comprehensive test suite in Cloud Build environment

steps:
  # Step 1: Install dependencies and setup
  - name: 'python:3.11-slim'
    id: 'setup'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio pytest-mock black ruff mypy safety bandit
        echo "Setup complete"

  # Step 2: Code formatting check
  - name: 'python:3.11-slim'
    id: 'format-check'
    entrypoint: 'bash'
    waitFor: ['setup']
    args:
      - '-c'
      - |
        echo "Running Black format check..."
        pip install black
        black --check src/ tests/ || {
          echo "Code formatting issues found. Run 'black src/ tests/' locally"
          exit 1
        }

  # Step 3: Linting
  - name: 'python:3.11-slim'
    id: 'lint'
    entrypoint: 'bash'
    waitFor: ['setup']
    args:
      - '-c'
      - |
        echo "Running Ruff linter..."
        pip install ruff
        ruff check src/ tests/ --output-format=github

  # Step 4: Type checking
  - name: 'python:3.11-slim'
    id: 'type-check'
    entrypoint: 'bash'
    waitFor: ['setup']
    args:
      - '-c'
      - |
        echo "Running MyPy type checker..."
        pip install mypy
        mypy src/ --ignore-missing-imports || {
          echo "Type checking completed with warnings"
          exit 0
        }

  # Step 5: Security scan - Dependencies
  - name: 'python:3.11-slim'
    id: 'security-deps'
    entrypoint: 'bash'
    waitFor: ['setup']
    args:
      - '-c'
      - |
        echo "Checking dependencies for vulnerabilities..."
        pip install safety
        safety check --file requirements.txt --json || {
          echo "Security vulnerabilities found in dependencies"
          exit 0  # Don't fail build, just warn
        }

  # Step 6: Security scan - Code
  - name: 'python:3.11-slim'
    id: 'security-code'
    entrypoint: 'bash'
    waitFor: ['setup']
    args:
      - '-c'
      - |
        echo "Scanning code for security issues..."
        pip install bandit
        bandit -r src/ -f json -o bandit-report.json || {
          echo "Security issues found in code"
          cat bandit-report.json
          exit 0  # Don't fail build, just warn
        }

  # Step 7: Unit tests
  - name: 'python:3.11-slim'
    id: 'unit-tests'
    entrypoint: 'bash'
    waitFor: ['format-check', 'lint']
    env:
      - 'ENVIRONMENT=test'
      - 'GCP_PROJECT_ID=${PROJECT_ID}'
      - 'BIGQUERY_LOCATION=US'
    args:
      - '-c'
      - |
        echo "Running unit tests..."
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio

        pytest tests/unit/ -v \
          --cov=src \
          --cov-report=term \
          --cov-report=xml \
          --cov-report=html \
          --tb=short \
          --maxfail=5

        echo "Unit tests completed"

  # Step 8: Integration tests
  - name: 'python:3.11-slim'
    id: 'integration-tests'
    entrypoint: 'bash'
    waitFor: ['unit-tests']
    env:
      - 'ENVIRONMENT=test'
      - 'GCP_PROJECT_ID=${PROJECT_ID}'
      - 'BIGQUERY_LOCATION=US'
    args:
      - '-c'
      - |
        echo "Running integration tests..."
        pip install -r requirements.txt
        pip install pytest pytest-asyncio

        pytest tests/integration/ -v \
          --tb=short \
          --maxfail=3 || {
          echo "Integration tests failed"
          exit 1
        }

        echo "Integration tests completed"

  # Step 9: Build Docker image for testing
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    waitFor: ['integration-tests']
    args:
      - 'build'
      - '-t'
      - 'test-image:${SHORT_SHA}'
      - '-f'
      - 'deployment/Dockerfile'
      - '.'

  # Step 10: Test Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-test'
    waitFor: ['docker-build']
    args:
      - 'run'
      - '--rm'
      - 'test-image:${SHORT_SHA}'
      - 'python'
      - '--version'

  # Step 11: Generate test report
  - name: 'python:3.11-slim'
    id: 'generate-report'
    waitFor: ['unit-tests', 'integration-tests']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "==================================="
        echo "Test Summary Report"
        echo "==================================="
        echo "Project: convergence-data-pipeline"
        echo "Build ID: ${BUILD_ID}"
        echo "Commit SHA: ${SHORT_SHA}"
        echo "Branch: ${BRANCH_NAME}"
        echo "==================================="
        echo "All tests passed successfully!"
        echo "==================================="

  # Step 12: Upload coverage to Cloud Storage (optional)
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-coverage'
    waitFor: ['generate-report']
    args:
      - 'cp'
      - '-r'
      - 'htmlcov/*'
      - 'gs://${PROJECT_ID}-test-reports/coverage/${SHORT_SHA}/'
    # Continue even if this fails
    allowFailure: true

# Timeout for entire build
timeout: 1800s

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true

# Artifacts
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-build-artifacts/tests/${SHORT_SHA}'
    paths:
      - 'coverage.xml'
      - 'bandit-report.json'
      - 'htmlcov/**'

# Substitutions
substitutions:
  _PYTHON_VERSION: '3.11'

# Available to build
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/test-credentials/versions/latest
      env: 'TEST_CREDENTIALS'
