// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "dashboard/index.mdx": () => import("../content/docs/dashboard/index.mdx?collection=docs"), "cost-analytics/cloud-costs.mdx": () => import("../content/docs/cost-analytics/cloud-costs.mdx?collection=docs"), "cost-analytics/genai-costs.mdx": () => import("../content/docs/cost-analytics/genai-costs.mdx?collection=docs"), "cost-analytics/index.mdx": () => import("../content/docs/cost-analytics/index.mdx?collection=docs"), "cost-analytics/subscription-costs.mdx": () => import("../content/docs/cost-analytics/subscription-costs.mdx?collection=docs"), "integrations/cloud-providers.mdx": () => import("../content/docs/integrations/cloud-providers.mdx?collection=docs"), "integrations/genai-providers.mdx": () => import("../content/docs/integrations/genai-providers.mdx?collection=docs"), "integrations/index.mdx": () => import("../content/docs/integrations/index.mdx?collection=docs"), "integrations/subscriptions.mdx": () => import("../content/docs/integrations/subscriptions.mdx?collection=docs"), "notifications/index.mdx": () => import("../content/docs/notifications/index.mdx?collection=docs"), "org-settings/billing.mdx": () => import("../content/docs/org-settings/billing.mdx?collection=docs"), "org-settings/hierarchy.mdx": () => import("../content/docs/org-settings/hierarchy.mdx?collection=docs"), "org-settings/index.mdx": () => import("../content/docs/org-settings/index.mdx?collection=docs"), "org-settings/organization.mdx": () => import("../content/docs/org-settings/organization.mdx?collection=docs"), "org-settings/quota-usage.mdx": () => import("../content/docs/org-settings/quota-usage.mdx?collection=docs"), "org-settings/team-members.mdx": () => import("../content/docs/org-settings/team-members.mdx?collection=docs"), "personal-settings/index.mdx": () => import("../content/docs/personal-settings/index.mdx?collection=docs"), "personal-settings/profile.mdx": () => import("../content/docs/personal-settings/profile.mdx?collection=docs"), "personal-settings/security.mdx": () => import("../content/docs/personal-settings/security.mdx?collection=docs"), "getting-started/account-setup.mdx": () => import("../content/docs/getting-started/account-setup.mdx?collection=docs"), "getting-started/index.mdx": () => import("../content/docs/getting-started/index.mdx?collection=docs"), "getting-started/quickstart.mdx": () => import("../content/docs/getting-started/quickstart.mdx?collection=docs"), "pipelines/cloud-runs.mdx": () => import("../content/docs/pipelines/cloud-runs.mdx?collection=docs"), "pipelines/genai-runs.mdx": () => import("../content/docs/pipelines/genai-runs.mdx?collection=docs"), "pipelines/index.mdx": () => import("../content/docs/pipelines/index.mdx?collection=docs"), "pipelines/subscription-runs.mdx": () => import("../content/docs/pipelines/subscription-runs.mdx?collection=docs"), }),
};
export default browserCollections;