"""
GenAI Pricing API Tests - Subscription and Pricing CRUD Operations

Tests for subscription and pricing endpoints with REAL test data (no mocking).

Test Categories:
1. Unit Tests (TestValidation) - Run without BigQuery, test Pydantic validation
2. Integration Tests (@pytest.mark.integration) - Require real BigQuery connection

Endpoints Tested:
- GET /api/v1/integrations/{org_slug}/{provider}/pricing
- GET /api/v1/integrations/{org_slug}/{provider}/pricing/{model_id}
- POST /api/v1/integrations/{org_slug}/{provider}/pricing
- PUT /api/v1/integrations/{org_slug}/{provider}/pricing/{model_id}
- DELETE /api/v1/integrations/{org_slug}/{provider}/pricing/{model_id}
- GET /api/v1/integrations/{org_slug}/{provider}/subscriptions
- GET /api/v1/integrations/{org_slug}/{provider}/subscriptions/{plan_name}
- POST /api/v1/integrations/{org_slug}/{provider}/subscriptions
- PUT /api/v1/integrations/{org_slug}/{provider}/subscriptions/{plan_name}
- DELETE /api/v1/integrations/{org_slug}/{provider}/subscriptions/{plan_name}

Providers: openai, anthropic, gemini

To run integration tests with real BigQuery:
    pytest tests/test_04_genai_pricing.py -m integration --run-integration

To run only unit tests (no BigQuery required):
    pytest tests/test_04_genai_pricing.py -m "not integration"
"""

import pytest
import uuid
from httpx import AsyncClient


# ============================================
# Test Data Fixtures
# ============================================

@pytest.fixture
def test_org_slug():
    """Test organization slug.

    For integration tests, use an existing org in BigQuery.
    For unit tests with mocking, any slug works.
    """
    import os
    # Use a real org slug for integration tests
    if os.environ.get("RUN_INTEGRATION_TESTS") == "true":
        return os.environ.get("TEST_ORG_SLUG", "guru_inc_12012025")
    return "test_org_123"


@pytest.fixture
def org_api_key():
    """Test organization API key.

    For integration tests, use a real API key.
    For unit tests with mocking, any key works.
    """
    import os
    if os.environ.get("RUN_INTEGRATION_TESTS") == "true":
        return os.environ.get("TEST_ORG_API_KEY", "test-api-key-for-integration")
    return "test_org_123_api_testkey1234567890"


@pytest.fixture
def test_pricing_openai():
    """Test OpenAI pricing data - custom model.

    Note: pricing_id, is_custom, is_enabled are auto-generated by the API.
    Only include fields accepted by OpenAIPricingCreate model.
    """
    return {
        "model_id": f"gpt-test-{uuid.uuid4().hex[:8]}",
        "model_name": "GPT Test Model",
        "input_price_per_1k": 0.005,
        "output_price_per_1k": 0.015,
        "effective_date": "2024-12-01",
        "notes": "Test pricing entry for integration tests"
    }


@pytest.fixture
def test_pricing_anthropic():
    """Test Anthropic pricing data - custom model.

    Note: Uses same base model as OpenAI. Provider-specific extended fields
    (x_anthropic_tier) are stored in BigQuery but not all may be accepted
    in the create request depending on the API model configuration.
    """
    return {
        "model_id": f"claude-test-{uuid.uuid4().hex[:8]}",
        "model_name": "Claude Test Model",
        "input_price_per_1k": 0.003,
        "output_price_per_1k": 0.012,
        "effective_date": "2024-12-01",
        "notes": "Test Anthropic pricing"
    }


@pytest.fixture
def test_pricing_gemini():
    """Test Gemini pricing data - custom model.

    Note: Uses same base model as OpenAI. Provider-specific extended fields
    (x_gemini_context_window, free_tier_*) are stored in BigQuery but not all
    may be accepted in the create request depending on the API model configuration.
    """
    return {
        "model_id": f"gemini-test-{uuid.uuid4().hex[:8]}",
        "model_name": "Gemini Test Model",
        "input_price_per_1k": 0.0001,
        "output_price_per_1k": 0.0004,
        "effective_date": "2024-12-01",
        "notes": "Test Gemini pricing"
    }


@pytest.fixture
def test_subscription_openai():
    """Test OpenAI subscription data - custom plan.

    Note: is_custom, is_enabled, auth_type are auto-set by API.
    Only include fields accepted by OpenAISubscriptionCreate model.
    """
    return {
        "subscription_id": f"sub_test_{uuid.uuid4().hex[:8]}",
        "plan_name": f"TEST_PLAN_{uuid.uuid4().hex[:6].upper()}",
        "quantity": 1,
        "unit_price": 0.0,
        "effective_date": "2024-12-01",
        "notes": "Test subscription for integration tests",
        "tier_type": "paid",
        "billing_period": "pay_as_you_go",
        "rpm_limit": 100,
        "tpm_limit": 50000,
        "rpd_limit": 5000
    }


@pytest.fixture
def test_subscription_anthropic():
    """Test Anthropic subscription data - custom plan."""
    return {
        "subscription_id": f"sub_test_{uuid.uuid4().hex[:8]}",
        "plan_name": f"TEST_ANTHROPIC_{uuid.uuid4().hex[:6].upper()}",
        "quantity": 1,
        "unit_price": 0.0,
        "effective_date": "2024-12-01",
        "notes": "Test Anthropic subscription",
        "tier_type": "paid",
        "billing_period": "pay_as_you_go",
        "rpm_limit": 50,
        "tpm_limit": 40000,
        "tpd_limit": 2000000
    }


@pytest.fixture
def test_subscription_gemini():
    """Test Gemini subscription data - custom plan."""
    return {
        "subscription_id": f"sub_test_{uuid.uuid4().hex[:8]}",
        "plan_name": f"TEST_GEMINI_{uuid.uuid4().hex[:6].upper()}",
        "quantity": 1,
        "unit_price": 0.0,
        "effective_date": "2024-12-01",
        "notes": "Test Gemini subscription",
        "tier_type": "paid",
        "billing_period": "pay_as_you_go",
        "rpm_limit": 360,
        "tpm_limit": 4000000,
        "trial_credit_usd": 300.0
    }


@pytest.fixture
def test_subscription_with_yearly_billing():
    """Test subscription with yearly billing."""
    return {
        "subscription_id": f"sub_yearly_{uuid.uuid4().hex[:8]}",
        "plan_name": f"YEARLY_PLAN_{uuid.uuid4().hex[:6].upper()}",
        "quantity": 5,
        "unit_price": 20.0,
        "effective_date": "2024-12-01",
        "notes": "Test yearly billing",
        "tier_type": "paid",
        "billing_period": "yearly",
        "yearly_price": 960.0,
        "yearly_discount_percentage": 20.0,
        "rpm_limit": 500,
        "tpm_limit": 100000
    }


@pytest.fixture
def test_subscription_trial():
    """Test subscription with trial period."""
    return {
        "subscription_id": f"sub_trial_{uuid.uuid4().hex[:8]}",
        "plan_name": f"TRIAL_PLAN_{uuid.uuid4().hex[:6].upper()}",
        "quantity": 1,
        "unit_price": 0.0,
        "effective_date": "2024-12-01",
        "notes": "Test trial subscription",
        "tier_type": "trial",
        "billing_period": "pay_as_you_go",
        "trial_end_date": "2025-01-01",
        "trial_credit_usd": 50.0,
        "rpm_limit": 10,
        "tpm_limit": 10000
    }


@pytest.fixture
def test_subscription_committed_use():
    """Test subscription with committed use discount (CUD)."""
    return {
        "subscription_id": f"sub_cud_{uuid.uuid4().hex[:8]}",
        "plan_name": f"CUD_PLAN_{uuid.uuid4().hex[:6].upper()}",
        "quantity": 1,
        "unit_price": 0.0,
        "effective_date": "2024-12-01",
        "notes": "Test CUD subscription",
        "tier_type": "committed_use",
        "billing_period": "yearly",
        "committed_spend_usd": 10000.0,
        "commitment_term_months": 12,
        "discount_percentage": 25.0,
        "rpm_limit": 1000,
        "tpm_limit": 500000
    }


# ============================================
# Pricing CRUD Tests - OpenAI
# ============================================

class TestPricingCRUD:
    """Test pricing CRUD operations."""

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_create_pricing_openai(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_pricing_openai: dict
    ):
        """Test creating a new OpenAI pricing entry."""
        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/pricing",
            headers={"X-API-Key": org_api_key},
            json=test_pricing_openai
        )

        assert response.status_code == 201, f"Failed: {response.text}"
        data = response.json()

        assert data["model_id"] == test_pricing_openai["model_id"]
        assert data["model_name"] == test_pricing_openai["model_name"]
        assert data["input_price_per_1k"] == test_pricing_openai["input_price_per_1k"]
        assert data["output_price_per_1k"] == test_pricing_openai["output_price_per_1k"]
        assert data["is_custom"] is True  # API-created entries are always custom
        assert data["is_enabled"] is True

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_list_pricing_openai(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test listing OpenAI pricing entries."""
        response = await async_client.get(
            f"/api/v1/integrations/{test_org_slug}/openai/pricing",
            headers={"X-API-Key": org_api_key}
        )

        assert response.status_code == 200
        data = response.json()

        assert "pricing" in data
        assert "count" in data
        assert data["org_slug"] == test_org_slug
        assert data["provider"] == "openai"

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_list_pricing_with_filters(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test listing pricing with filters."""
        # Filter by enabled status
        response = await async_client.get(
            f"/api/v1/integrations/{test_org_slug}/openai/pricing",
            headers={"X-API-Key": org_api_key},
            params={"is_enabled": True, "include_custom": True}
        )

        assert response.status_code == 200
        data = response.json()

        # All returned items should be enabled
        for item in data["pricing"]:
            assert item.get("is_enabled", True) is True

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_get_single_pricing(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_pricing_openai: dict
    ):
        """Test getting a single pricing entry."""
        # First create
        create_response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/pricing",
            headers={"X-API-Key": org_api_key},
            json=test_pricing_openai
        )
        assert create_response.status_code == 201

        # Then get
        response = await async_client.get(
            f"/api/v1/integrations/{test_org_slug}/openai/pricing/{test_pricing_openai['model_id']}",
            headers={"X-API-Key": org_api_key}
        )

        assert response.status_code == 200
        data = response.json()
        assert data["model_id"] == test_pricing_openai["model_id"]

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_update_pricing(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_pricing_openai: dict
    ):
        """Test updating a pricing entry."""
        # First create
        create_response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/pricing",
            headers={"X-API-Key": org_api_key},
            json=test_pricing_openai
        )
        assert create_response.status_code == 201

        # Update with new prices
        update_data = {
            "input_price_per_1k": 0.01,
            "output_price_per_1k": 0.03,
            "notes": "Updated pricing"
        }

        response = await async_client.put(
            f"/api/v1/integrations/{test_org_slug}/openai/pricing/{test_pricing_openai['model_id']}",
            headers={"X-API-Key": org_api_key},
            json=update_data
        )

        assert response.status_code == 200
        data = response.json()
        assert data["input_price_per_1k"] == 0.01
        assert data["output_price_per_1k"] == 0.03
        assert data["notes"] == "Updated pricing"

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_delete_pricing(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_pricing_openai: dict
    ):
        """Test deleting a pricing entry."""
        # First create
        create_response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/pricing",
            headers={"X-API-Key": org_api_key},
            json=test_pricing_openai
        )
        assert create_response.status_code == 201

        # Delete
        response = await async_client.delete(
            f"/api/v1/integrations/{test_org_slug}/openai/pricing/{test_pricing_openai['model_id']}",
            headers={"X-API-Key": org_api_key}
        )

        # 204 No Content is the standard REST response for successful DELETE
        assert response.status_code in [200, 204], f"Expected 200 or 204, got {response.status_code}"

        # Verify deleted - should return 404
        get_response = await async_client.get(
            f"/api/v1/integrations/{test_org_slug}/openai/pricing/{test_pricing_openai['model_id']}",
            headers={"X-API-Key": org_api_key}
        )
        assert get_response.status_code == 404

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_create_pricing_anthropic(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_pricing_anthropic: dict
    ):
        """Test creating Anthropic pricing entry."""
        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/anthropic/pricing",
            headers={"X-API-Key": org_api_key},
            json=test_pricing_anthropic
        )

        assert response.status_code == 201, f"Failed: {response.text}"
        data = response.json()
        assert data["model_id"] == test_pricing_anthropic["model_id"]
        assert data["is_custom"] is True

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_create_pricing_gemini(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_pricing_gemini: dict
    ):
        """Test creating Gemini pricing entry."""
        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/gemini/pricing",
            headers={"X-API-Key": org_api_key},
            json=test_pricing_gemini
        )

        assert response.status_code == 201, f"Failed: {response.text}"
        data = response.json()
        assert data["model_id"] == test_pricing_gemini["model_id"]
        assert data["is_custom"] is True


# ============================================
# Subscription CRUD Tests
# ============================================

class TestSubscriptionCRUD:
    """Test subscription CRUD operations."""

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_create_subscription_openai(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_subscription_openai: dict
    ):
        """Test creating a new OpenAI subscription."""
        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key},
            json=test_subscription_openai
        )

        assert response.status_code == 201, f"Failed: {response.text}"
        data = response.json()

        assert data["plan_name"] == test_subscription_openai["plan_name"]
        assert data["quantity"] == test_subscription_openai["quantity"]
        assert data["billing_period"] == test_subscription_openai["billing_period"]
        assert data["tier_type"] == test_subscription_openai["tier_type"]
        assert data["rpm_limit"] == test_subscription_openai["rpm_limit"]
        assert data["tpm_limit"] == test_subscription_openai["tpm_limit"]
        assert data["is_custom"] is True

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_list_subscriptions(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test listing subscriptions."""
        response = await async_client.get(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key}
        )

        assert response.status_code == 200
        data = response.json()

        assert "subscriptions" in data
        assert "count" in data
        assert data["org_slug"] == test_org_slug
        assert data["provider"] == "openai"

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_get_single_subscription(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_subscription_openai: dict
    ):
        """Test getting a single subscription."""
        # First create
        create_response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key},
            json=test_subscription_openai
        )
        assert create_response.status_code == 201

        # Then get
        response = await async_client.get(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions/{test_subscription_openai['plan_name']}",
            headers={"X-API-Key": org_api_key}
        )

        assert response.status_code == 200
        data = response.json()
        assert data["plan_name"] == test_subscription_openai["plan_name"]

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_update_subscription(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_subscription_openai: dict
    ):
        """Test updating a subscription."""
        # First create
        create_response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key},
            json=test_subscription_openai
        )
        assert create_response.status_code == 201

        # Update
        update_data = {
            "quantity": 10,
            "rpm_limit": 200,
            "tpm_limit": 100000,
            "notes": "Updated subscription"
        }

        response = await async_client.put(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions/{test_subscription_openai['plan_name']}",
            headers={"X-API-Key": org_api_key},
            json=update_data
        )

        assert response.status_code == 200
        data = response.json()
        assert data["quantity"] == 10
        assert data["rpm_limit"] == 200
        assert data["tpm_limit"] == 100000

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_delete_subscription(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_subscription_openai: dict
    ):
        """Test deleting a subscription."""
        # First create
        create_response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key},
            json=test_subscription_openai
        )
        assert create_response.status_code == 201

        # Delete
        response = await async_client.delete(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions/{test_subscription_openai['plan_name']}",
            headers={"X-API-Key": org_api_key}
        )

        # 204 No Content is the standard REST response for successful DELETE
        assert response.status_code in [200, 204], f"Expected 200 or 204, got {response.status_code}"

        # Verify deleted
        get_response = await async_client.get(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions/{test_subscription_openai['plan_name']}",
            headers={"X-API-Key": org_api_key}
        )
        assert get_response.status_code == 404

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_create_subscription_anthropic(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_subscription_anthropic: dict
    ):
        """Test creating Anthropic subscription."""
        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/anthropic/subscriptions",
            headers={"X-API-Key": org_api_key},
            json=test_subscription_anthropic
        )

        assert response.status_code == 201, f"Failed: {response.text}"
        data = response.json()
        assert data["plan_name"] == test_subscription_anthropic["plan_name"]
        assert data["tpd_limit"] == test_subscription_anthropic["tpd_limit"]

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_create_subscription_gemini(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_subscription_gemini: dict
    ):
        """Test creating Gemini subscription."""
        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/gemini/subscriptions",
            headers={"X-API-Key": org_api_key},
            json=test_subscription_gemini
        )

        assert response.status_code == 201, f"Failed: {response.text}"
        data = response.json()
        assert data["plan_name"] == test_subscription_gemini["plan_name"]
        assert data["trial_credit_usd"] == test_subscription_gemini["trial_credit_usd"]


# ============================================
# Subscription Billing Period Tests
# ============================================

class TestSubscriptionBillingPeriods:
    """Test subscription billing period variations."""

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_create_yearly_subscription(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_subscription_with_yearly_billing: dict
    ):
        """Test creating subscription with yearly billing."""
        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key},
            json=test_subscription_with_yearly_billing
        )

        assert response.status_code == 201, f"Failed: {response.text}"
        data = response.json()

        assert data["billing_period"] == "yearly"
        assert data["yearly_price"] == 960.0
        assert data["yearly_discount_percentage"] == 20.0
        assert data["quantity"] == 5
        assert data["unit_price"] == 20.0

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_create_trial_subscription(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_subscription_trial: dict
    ):
        """Test creating subscription with trial period."""
        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key},
            json=test_subscription_trial
        )

        assert response.status_code == 201, f"Failed: {response.text}"
        data = response.json()

        assert data["tier_type"] == "trial"
        assert data["trial_credit_usd"] == 50.0
        assert data["trial_end_date"] == "2025-01-01"

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_create_committed_use_subscription(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str,
        test_subscription_committed_use: dict
    ):
        """Test creating subscription with committed use discount."""
        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/gemini/subscriptions",
            headers={"X-API-Key": org_api_key},
            json=test_subscription_committed_use
        )

        assert response.status_code == 201, f"Failed: {response.text}"
        data = response.json()

        assert data["tier_type"] == "committed_use"
        assert data["committed_spend_usd"] == 10000.0
        assert data["commitment_term_months"] == 12
        assert data["discount_percentage"] == 25.0


# ============================================
# Validation Tests
# ============================================

class TestValidation:
    """Test input validation."""

    @pytest.mark.asyncio
    async def test_invalid_provider(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test that invalid provider is rejected."""
        response = await async_client.get(
            f"/api/v1/integrations/{test_org_slug}/invalid_provider/pricing",
            headers={"X-API-Key": org_api_key}
        )

        # 401/403 for auth failures (invalid API key), 404/422 for invalid provider
        assert response.status_code in [401, 403, 404, 422]

    @pytest.mark.asyncio
    async def test_negative_price(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test that negative prices are rejected."""
        invalid_pricing = {
            "pricing_id": "price_invalid",
            "model_id": "test-model",
            "model_name": "Test",
            "input_price_per_1k": -0.01,  # Negative - invalid
            "output_price_per_1k": 0.01,
            "effective_date": "2024-12-01"
        }

        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/pricing",
            headers={"X-API-Key": org_api_key},
            json=invalid_pricing
        )

        # 401/403 for auth failures, 422 for validation error
        assert response.status_code in [401, 403, 422]

    @pytest.mark.asyncio
    async def test_invalid_billing_period(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test that invalid billing period is rejected."""
        invalid_subscription = {
            "subscription_id": "sub_invalid",
            "plan_name": "INVALID_PLAN",
            "quantity": 1,
            "unit_price": 10.0,
            "effective_date": "2024-12-01",
            "billing_period": "biweekly"  # Invalid - not in enum
        }

        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key},
            json=invalid_subscription
        )

        # 401/403 for auth failures, 422 for validation error
        assert response.status_code in [401, 403, 422]

    @pytest.mark.asyncio
    async def test_invalid_tier_type(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test that invalid tier type is rejected."""
        invalid_subscription = {
            "subscription_id": "sub_invalid",
            "plan_name": "INVALID_TIER",
            "quantity": 1,
            "unit_price": 10.0,
            "effective_date": "2024-12-01",
            "tier_type": "premium"  # Invalid - not in enum
        }

        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key},
            json=invalid_subscription
        )

        # 401/403 for auth failures, 422 for validation error
        assert response.status_code in [401, 403, 422]

    @pytest.mark.asyncio
    async def test_negative_quantity(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test that negative quantity is rejected."""
        invalid_subscription = {
            "subscription_id": "sub_neg",
            "plan_name": "NEG_QTY",
            "quantity": -5,  # Negative - invalid
            "unit_price": 10.0,
            "effective_date": "2024-12-01"
        }

        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key},
            json=invalid_subscription
        )

        # 401/403 for auth failures, 422 for validation error
        assert response.status_code in [401, 403, 422]


# ============================================
# Edge Cases and Error Handling
# ============================================

class TestEdgeCases:
    """Test edge cases and error handling."""

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_get_nonexistent_pricing(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test getting pricing that doesn't exist."""
        response = await async_client.get(
            f"/api/v1/integrations/{test_org_slug}/openai/pricing/nonexistent-model-xyz",
            headers={"X-API-Key": org_api_key}
        )

        assert response.status_code == 404

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_get_nonexistent_subscription(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test getting subscription that doesn't exist."""
        response = await async_client.get(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions/NONEXISTENT_PLAN",
            headers={"X-API-Key": org_api_key}
        )

        assert response.status_code == 404

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_delete_nonexistent_pricing(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test deleting pricing that doesn't exist.

        Note: The API may return 204 even for non-existent records (idempotent delete)
        or 404 if it validates existence first. Both are acceptable REST patterns.
        """
        response = await async_client.delete(
            f"/api/v1/integrations/{test_org_slug}/openai/pricing/nonexistent-model",
            headers={"X-API-Key": org_api_key}
        )

        # Accept both 204 (idempotent) or 404 (strict validation)
        assert response.status_code in [204, 404], f"Expected 204 or 404, got {response.status_code}"

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_pagination(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test pagination on list endpoints."""
        # Test with limit and offset
        response = await async_client.get(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key},
            params={"limit": 5, "offset": 0}
        )

        assert response.status_code == 200
        data = response.json()
        assert len(data["subscriptions"]) <= 5

    @pytest.mark.asyncio
    async def test_invalid_pagination_negative_limit(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test that negative limit is rejected."""
        response = await async_client.get(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key},
            params={"limit": -1}
        )

        # 401/403 for auth failures, 400/422 for validation error
        assert response.status_code in [400, 401, 403, 422]

    @pytest.mark.asyncio
    async def test_invalid_pagination_negative_offset(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test that negative offset is rejected."""
        response = await async_client.get(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key},
            params={"offset": -1}
        )

        # 401/403 for auth failures, 400/422 for validation error
        assert response.status_code in [400, 401, 403, 422]


# ============================================
# Rate Limit Field Validation Tests
# ============================================

class TestRateLimitFields:
    """Test rate limit field validations (RPM, TPM, RPD, TPD)."""

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_subscription_with_all_rate_limits(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test creating subscription with all rate limit fields."""
        subscription = {
            "subscription_id": f"sub_rate_{uuid.uuid4().hex[:8]}",
            "plan_name": f"RATE_TEST_{uuid.uuid4().hex[:6].upper()}",
            "quantity": 1,
            "unit_price": 0.0,
            "effective_date": "2024-12-01",
            "billing_period": "pay_as_you_go",
            "tier_type": "paid",
            "rpm_limit": 500,        # Requests per minute
            "tpm_limit": 100000,     # Tokens per minute
            "rpd_limit": 10000,      # Requests per day
            "tpd_limit": 5000000,    # Tokens per day
            "concurrent_limit": 10   # Max concurrent requests
        }

        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key},
            json=subscription
        )

        assert response.status_code == 201, f"Failed: {response.text}"
        data = response.json()

        assert data["rpm_limit"] == 500
        assert data["tpm_limit"] == 100000
        assert data["rpd_limit"] == 10000
        assert data["tpd_limit"] == 5000000
        assert data["concurrent_limit"] == 10

    @pytest.mark.integration
    @pytest.mark.asyncio
    async def test_subscription_with_token_limits(
        self,
        async_client: AsyncClient,
        org_api_key: str,
        test_org_slug: str
    ):
        """Test creating subscription with daily/monthly token limits."""
        subscription = {
            "subscription_id": f"sub_token_{uuid.uuid4().hex[:8]}",
            "plan_name": f"TOKEN_TEST_{uuid.uuid4().hex[:6].upper()}",
            "quantity": 1,
            "unit_price": 0.0,
            "effective_date": "2024-12-01",
            "billing_period": "monthly",
            "tier_type": "paid",
            "daily_token_limit": 1000000,
            "monthly_token_limit": 30000000
        }

        response = await async_client.post(
            f"/api/v1/integrations/{test_org_slug}/openai/subscriptions",
            headers={"X-API-Key": org_api_key},
            json=subscription
        )

        assert response.status_code == 201, f"Failed: {response.text}"
        data = response.json()

        assert data["daily_token_limit"] == 1000000
        assert data["monthly_token_limit"] == 30000000
