# Cloud Build Trigger: Deploy to Production
# Triggered on: Tag matching v* (e.g., v3.0.5, v1.0.0)
# Deploys: All services (api-service, pipeline-service, chat-backend, frontend) to prod

substitutions:
  _ENV: prod
  _PROJECT_ID: cloudact-prod
  _REGION: us-central1
  # Supabase (production instance)
  _SUPABASE_URL: https://ovfxswhkkshouhsryzaf.supabase.co
  _SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92Znhzd2hra3Nob3Voc3J5emFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMjk4NDEsImV4cCI6MjA3OTYwNTg0MX0.qj1X5HDM7DckMtQH8ktlWrKCVFqqiZMeshiRp8tX_z4
  # Stripe (LIVE keys for production)
  _STRIPE_PUBLISHABLE_KEY: pk_live_51STncwDoxINmrJKYoK1MKkwIHBDchc7HvXXDgvnruaXpHEOc1e2LH8FuDiqzo313P9FrjbitcUzQGS4x5VAixt5u00IRZy5m8g
  _STRIPE_STARTER_PRICE_ID: price_1SWJMfDoxINmrJKY7tOoJUIs
  _STRIPE_PROFESSIONAL_PRICE_ID: price_1SWJOYDoxINmrJKY8jEZwVuU
  _STRIPE_SCALE_PRICE_ID: price_1SWJP8DoxINmrJKYfg0jmeLv

steps:
  # ============================================
  # Build All Services in Parallel
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api-service'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '--build-arg=TARGET_ENV=${_ENV}'
      - '--build-arg=VERSION=${TAG_NAME}'
      - '--build-arg=BUILD_DATE=$BUILD_ID'
      - '--build-arg=GIT_COMMIT=${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/cloudact-api-service-${_ENV}:${TAG_NAME}'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/cloudact-api-service-${_ENV}:latest'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/cloudact-api-service-${_ENV}:${_ENV}-latest'
      - '-f'
      - '02-api-service/Dockerfile'
      - '02-api-service'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api-service'
    args: ['push', '--all-tags', 'gcr.io/${_PROJECT_ID}/cloudact-api-service-${_ENV}']
    waitFor: ['build-api-service']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-pipeline-service'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '--build-arg=TARGET_ENV=${_ENV}'
      - '--build-arg=VERSION=${TAG_NAME}'
      - '--build-arg=BUILD_DATE=$BUILD_ID'
      - '--build-arg=GIT_COMMIT=${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/cloudact-pipeline-service-${_ENV}:${TAG_NAME}'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/cloudact-pipeline-service-${_ENV}:latest'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/cloudact-pipeline-service-${_ENV}:${_ENV}-latest'
      - '-f'
      - '03-data-pipeline-service/Dockerfile'
      - '03-data-pipeline-service'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-pipeline-service'
    args: ['push', '--all-tags', 'gcr.io/${_PROJECT_ID}/cloudact-pipeline-service-${_ENV}']
    waitFor: ['build-pipeline-service']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-chat-backend'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '--build-arg=TARGET_ENV=${_ENV}'
      - '--build-arg=VERSION=${TAG_NAME}'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/cloudact-chat-backend-${_ENV}:${TAG_NAME}'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/cloudact-chat-backend-${_ENV}:latest'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/cloudact-chat-backend-${_ENV}:${_ENV}-latest'
      - '-f'
      - '07-org-chat-backend/Dockerfile'
      - '07-org-chat-backend'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-chat-backend'
    args: ['push', '--all-tags', 'gcr.io/${_PROJECT_ID}/cloudact-chat-backend-${_ENV}']
    waitFor: ['build-chat-backend']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '--build-arg=TARGET_ENV=${_ENV}'
      - '--build-arg=VERSION=${TAG_NAME}'
      - '--build-arg=BUILD_DATE=$BUILD_ID'
      - '--build-arg=GIT_COMMIT=${SHORT_SHA}'
      - '--build-arg=NEXT_PUBLIC_SUPABASE_URL=${_SUPABASE_URL}'
      - '--build-arg=NEXT_PUBLIC_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}'
      - '--build-arg=NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_STRIPE_PUBLISHABLE_KEY}'
      - '--build-arg=NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID=${_STRIPE_STARTER_PRICE_ID}'
      - '--build-arg=NEXT_PUBLIC_STRIPE_PROFESSIONAL_PRICE_ID=${_STRIPE_PROFESSIONAL_PRICE_ID}'
      - '--build-arg=NEXT_PUBLIC_STRIPE_SCALE_PRICE_ID=${_STRIPE_SCALE_PRICE_ID}'
      - '--build-arg=NEXT_PUBLIC_API_SERVICE_URL=https://api.cloudact.ai'
      - '--build-arg=NEXT_PUBLIC_PIPELINE_SERVICE_URL=https://pipeline.cloudact.ai'
      - '--build-arg=NEXT_PUBLIC_APP_URL=https://cloudact.ai'
      - '--build-arg=NEXT_PUBLIC_DEFAULT_TRIAL_DAYS=14'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/cloudact-frontend-${_ENV}:${TAG_NAME}'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/cloudact-frontend-${_ENV}:latest'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/cloudact-frontend-${_ENV}:${_ENV}-latest'
      - '-f'
      - '01-fronted-system/Dockerfile'
      - '01-fronted-system'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args: ['push', '--all-tags', 'gcr.io/${_PROJECT_ID}/cloudact-frontend-${_ENV}']
    waitFor: ['build-frontend']

  # ============================================
  # Build Scheduler Jobs Image
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-jobs'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '--build-arg=TARGET_ENV=${_ENV}'
      - '--build-arg=VERSION=${TAG_NAME}'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/cloudact-jobs-${_ENV}:${TAG_NAME}'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/cloudact-jobs-${_ENV}:latest'
      - '-f'
      - '05-scheduler-jobs/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-jobs'
    args: ['push', '--all-tags', 'gcr.io/${_PROJECT_ID}/cloudact-jobs-${_ENV}']
    waitFor: ['build-jobs']

  # ============================================
  # Deploy API Service
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get pipeline service URL (use custom domain for prod)
        PIPELINE_URL="https://pipeline.cloudact.ai"
        
        gcloud run deploy cloudact-api-service-${_ENV} \
          --project=${_PROJECT_ID} \
          --image=gcr.io/${_PROJECT_ID}/cloudact-api-service-${_ENV}:${TAG_NAME} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=8Gi \
          --cpu=2 \
          --timeout=300 \
          --min-instances=1 \
          --max-instances=10 \
          --port=8000 \
          --service-account=cloudact-sa-${_ENV}@${_PROJECT_ID}.iam.gserviceaccount.com \
          --set-env-vars="GCP_PROJECT_ID=${_PROJECT_ID},BIGQUERY_LOCATION=US,ENVIRONMENT=production,PIPELINE_SERVICE_URL=$$PIPELINE_URL,KMS_PROJECT_ID=${_PROJECT_ID},KMS_LOCATION=us-central1,KMS_KEYRING=cloudact-keyring,KMS_KEY=api-key-encryption,SUPABASE_URL=${_SUPABASE_URL}" \
          --set-secrets=CA_ROOT_API_KEY=ca-root-api-key-${_ENV}:latest,SUPABASE_SERVICE_ROLE_KEY=supabase-service-role-key-${_ENV}:latest
    waitFor: ['push-api-service']

  # ============================================
  # Deploy Pipeline Service
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-pipeline-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get API service URL (use custom domain for prod)
        API_URL="https://api.cloudact.ai"

        gcloud run deploy cloudact-pipeline-service-${_ENV} \
          --project=${_PROJECT_ID} \
          --image=gcr.io/${_PROJECT_ID}/cloudact-pipeline-service-${_ENV}:${TAG_NAME} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=8Gi \
          --cpu=2 \
          --timeout=300 \
          --min-instances=1 \
          --max-instances=10 \
          --port=8001 \
          --service-account=cloudact-sa-${_ENV}@${_PROJECT_ID}.iam.gserviceaccount.com \
          --set-env-vars="GCP_PROJECT_ID=${_PROJECT_ID},BIGQUERY_LOCATION=US,ENVIRONMENT=production,API_SERVICE_URL=$$API_URL,KMS_PROJECT_ID=${_PROJECT_ID},KMS_LOCATION=us-central1,KMS_KEYRING=cloudact-keyring,KMS_KEY=api-key-encryption,SMTP_HOST=smtp.gmail.com,SMTP_PORT=587,SMTP_USERNAME=support@cloudact.ai,FROM_EMAIL=alerts@cloudact.ai,FROM_NAME=CloudAct.AI" \
          --set-secrets=CA_ROOT_API_KEY=ca-root-api-key-${_ENV}:latest,SMTP_PASSWORD=smtp-password-${_ENV}:latest
    waitFor: ['push-pipeline-service']

  # ============================================
  # Deploy Chat Backend (internal service)
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-chat-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy cloudact-chat-backend-${_ENV} \
          --project=${_PROJECT_ID} \
          --image=gcr.io/${_PROJECT_ID}/cloudact-chat-backend-${_ENV}:${TAG_NAME} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=4Gi \
          --cpu=2 \
          --timeout=120 \
          --min-instances=1 \
          --max-instances=10 \
          --port=8002 \
          --service-account=cloudact-sa-${_ENV}@${_PROJECT_ID}.iam.gserviceaccount.com \
          --set-env-vars="GCP_PROJECT_ID=${_PROJECT_ID},BIGQUERY_LOCATION=US,ENVIRONMENT=production,ORGANIZATIONS_DATASET=organizations,KMS_PROJECT_ID=${_PROJECT_ID},KMS_LOCATION=us-central1,KMS_KEYRING=cloudact-keyring,KMS_KEY=api-key-encryption,CORS_ORIGINS=https://cloudact.ai,SUPABASE_URL=${_SUPABASE_URL}" \
          --set-secrets=CA_ROOT_API_KEY=ca-root-api-key-${_ENV}:latest,SUPABASE_SERVICE_ROLE_KEY=supabase-service-role-key-${_ENV}:latest
    waitFor: ['push-chat-backend']

  # ============================================
  # Deploy Frontend
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Use custom domains for prod
        API_URL="https://api.cloudact.ai"
        PIPELINE_URL="https://pipeline.cloudact.ai"
        APP_URL="https://cloudact.ai"
        CHAT_URL=$$(gcloud run services describe cloudact-chat-backend-${_ENV} --project=${_PROJECT_ID} --region=${_REGION} --format="value(status.url)" 2>/dev/null || echo "https://cloudact-chat-backend-${_ENV}.${_REGION}.run.app")

        # Clear secret-bound env vars before setting as plain env vars
        # These were previously set as secrets but should be plain env vars (baked into image at build time)
        gcloud run services update cloudact-frontend-${_ENV} \
          --project=${_PROJECT_ID} \
          --region=${_REGION} \
          --remove-secrets="NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,supabase-anon-key-${_ENV},stripe-publishable-key-${_ENV}" \
          --quiet 2>/dev/null || true

        gcloud run deploy cloudact-frontend-${_ENV} \
          --project=${_PROJECT_ID} \
          --image=gcr.io/${_PROJECT_ID}/cloudact-frontend-${_ENV}:${TAG_NAME} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=2Gi \
          --cpu=2 \
          --timeout=60 \
          --min-instances=1 \
          --max-instances=10 \
          --port=3000 \
          --service-account=cloudact-sa-${_ENV}@${_PROJECT_ID}.iam.gserviceaccount.com \
          --set-env-vars="GCP_PROJECT_ID=${_PROJECT_ID},ENVIRONMENT=production,NODE_ENV=production,NEXT_PUBLIC_API_SERVICE_URL=$$API_URL,API_SERVICE_URL=$$API_URL,NEXT_PUBLIC_PIPELINE_SERVICE_URL=$$PIPELINE_URL,PIPELINE_SERVICE_URL=$$PIPELINE_URL,NEXT_PUBLIC_APP_URL=$$APP_URL,CHAT_BACKEND_URL=$$CHAT_URL,NEXT_PUBLIC_SUPABASE_URL=${_SUPABASE_URL},NEXT_PUBLIC_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY},NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_STRIPE_PUBLISHABLE_KEY},NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID=${_STRIPE_STARTER_PRICE_ID},NEXT_PUBLIC_STRIPE_PROFESSIONAL_PRICE_ID=${_STRIPE_PROFESSIONAL_PRICE_ID},NEXT_PUBLIC_STRIPE_SCALE_PRICE_ID=${_STRIPE_SCALE_PRICE_ID},NEXT_PUBLIC_DEFAULT_TRIAL_DAYS=14,SMTP_HOST=smtp.gmail.com,SMTP_PORT=587,SMTP_USERNAME=support@cloudact.ai,FROM_EMAIL=support@cloudact.ai,FROM_NAME=CloudAct.ai Support" \
          --set-secrets=CA_ROOT_API_KEY=ca-root-api-key-${_ENV}:latest,STRIPE_SECRET_KEY=stripe-secret-key-${_ENV}:latest,STRIPE_WEBHOOK_SECRET=stripe-webhook-secret-${_ENV}:latest,SUPABASE_SERVICE_ROLE_KEY=supabase-service-role-key-${_ENV}:latest,SMTP_PASSWORD=smtp-password-${_ENV}:latest
    waitFor: ['push-frontend', 'deploy-api-service', 'deploy-pipeline-service', 'deploy-chat-backend']

  # ============================================
  # Update Cloud Run Jobs with New Image
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'update-jobs'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Update all Cloud Run jobs to use the new image
        # Job names match create-all-jobs.sh (manual + daily + monthly)
        JOBS="cloudact-manual-supabase-migrate cloudact-manual-bootstrap cloudact-manual-org-sync-all cloudact-daily-quota-reset cloudact-daily-quota-cleanup cloudact-daily-stale-cleanup cloudact-daily-pipelines cloudact-daily-alerts cloudact-monthly-quota-reset"

        for JOB in $$JOBS; do
          if gcloud run jobs describe $$JOB --region=${_REGION} --project=${_PROJECT_ID} &>/dev/null; then
            echo "Updating job: $$JOB"
            gcloud run jobs update $$JOB \
              --region=${_REGION} \
              --project=${_PROJECT_ID} \
              --image=gcr.io/${_PROJECT_ID}/cloudact-jobs-${_ENV}:${TAG_NAME} \
              --quiet || echo "Warning: Failed to update $$JOB"
          else
            echo "Job $$JOB does not exist, skipping"
          fi
        done

        echo "Jobs image update complete"
    waitFor: ['push-jobs']

# Push all images
images:
  - 'gcr.io/${_PROJECT_ID}/cloudact-api-service-${_ENV}:${TAG_NAME}'
  - 'gcr.io/${_PROJECT_ID}/cloudact-api-service-${_ENV}:latest'
  - 'gcr.io/${_PROJECT_ID}/cloudact-api-service-${_ENV}:${_ENV}-latest'
  - 'gcr.io/${_PROJECT_ID}/cloudact-pipeline-service-${_ENV}:${TAG_NAME}'
  - 'gcr.io/${_PROJECT_ID}/cloudact-pipeline-service-${_ENV}:latest'
  - 'gcr.io/${_PROJECT_ID}/cloudact-pipeline-service-${_ENV}:${_ENV}-latest'
  - 'gcr.io/${_PROJECT_ID}/cloudact-frontend-${_ENV}:${TAG_NAME}'
  - 'gcr.io/${_PROJECT_ID}/cloudact-frontend-${_ENV}:latest'
  - 'gcr.io/${_PROJECT_ID}/cloudact-frontend-${_ENV}:${_ENV}-latest'
  - 'gcr.io/${_PROJECT_ID}/cloudact-chat-backend-${_ENV}:${TAG_NAME}'
  - 'gcr.io/${_PROJECT_ID}/cloudact-chat-backend-${_ENV}:latest'
  - 'gcr.io/${_PROJECT_ID}/cloudact-chat-backend-${_ENV}:${_ENV}-latest'
  - 'gcr.io/${_PROJECT_ID}/cloudact-jobs-${_ENV}:${TAG_NAME}'
  - 'gcr.io/${_PROJECT_ID}/cloudact-jobs-${_ENV}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '3600s'
